{{- /* TODO(aylei): remove backward compatibility in 0.12.0 */ -}}
{{- $enableBasicAuthInAPIServer := include "skypilot.enableBasicAuthInAPIServer" . | trim | eq "true" -}}
{{- if and (not .Values.ingress.authSecret) .Values.ingress.authCredentials (not $enableBasicAuthInAPIServer) (not (index .Values.ingress "oauth2-proxy" "enabled")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-basic-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  auth: {{ .Values.ingress.authCredentials | quote }}
{{- end }}
