{{- if and (include "skypilot.enableBasicAuthInAPIServer" . | trim | eq "true") (not .Values.apiService.initialBasicAuthSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-initial-basic-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  auth: {{ .Values.apiService.initialBasicAuthCredentials | quote }}
{{- end }}
