# Models to evaluate
models:
  # Public model from HuggingFace
  - name: "mistral-7b"
    source: "huggingface"
    model_id: "mistralai/Mistral-7B-Instruct-v0.3"
    accelerators: "L4:1"
    
  # Custom model from S3 bucket
  - name: "agent-qwen"
    source: "s3://my-models/qwen-7b-agent"
    accelerators: "L4:1"
    
  # Model from SkyPilot volume
  - name: "agent-llama"
    source: "volume://model-checkpoints/agent-llama"
    accelerators: "L4:1"

# Cleanup clusters after evaluation
cleanup_on_complete: true
