# service.yaml
# The newly-added `service` section to the `serve-openai-api.yaml` file.
service:
  # Specifying the path to the endpoint to check the readiness of the service.
  readiness_probe: /v1/models
  # How many replicas to manage.
  replicas: 2

# Fields below are the same with `serve-openai-api.yaml`.
envs:
  MODEL_NAME: meta-llama/Llama-3.2-1B-Instruct
secrets:
  HF_TOKEN: null # Pass with `--secret HF_TOKEN` in CLI

resources:
  accelerators: {L4:1, A10G:1, A10:1, A100:1, A100-80GB:1}
  ports:
    - 8000

setup: |
  uv venv --python 3.10 --seed
  source .venv/bin/activate

  uv pip install "vllm>=0.8.3"

  python -c "import huggingface_hub; huggingface_hub.login('${HF_TOKEN}')"


run: |
  source .venv/bin/activate
  echo 'Starting vllm openai api server...'
  vllm serve $MODEL_NAME \
    --port 8000 \
    --dtype auto \
    --tensor-parallel-size $SKYPILOT_NUM_GPUS_PER_NODE

